package com.chinmay.enums;

public enum ConfigProperties {
    REMOTE_URL,
    LOCAL_URL,
    OVERRIDEREPORTS,
    PASSEDSCREENSHOT,
    FAILEDSCREENSHOT,
    RETRYFAILEDTEST,
    SKIPPPEDSCREENSHOT,
    HOSTNAME,
    MAILAUTHENTICATOR,
    MAILPASSWORD,
    MANAGER,
    MANAGERNAME,
    MAILSUBJECT,
    MAILBODY,
    SETFROMMAIL,
    SETFROMNAME,
    SEND_RESULTS_TO_DASHBOARD,
    SEND_REPORTS_MAIL,
    VIDEO_RECORD,
    TAKE_SCREENSHOT_PASS,
    TAKE_SCREENSHOT_FAIL,
    TAKE_SCREENSHOT_SKIP,
    SCREENSHOT_ALL_STEPS,
    DATA_SOURCE;
}
